### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by fatihd** [iQuarc/Geco#2]
I need a standard getting started documentation, that will get to a running code.

**Comment by popcatalin81** [comment]
Thank you for your suggestion @fatihd I will begin working on documentation this week.
Here are some quick hints until then:

If running from Visual Studio using the Project template from the marketplace is the easiest starting option.

1. Download from [Marketplace](https://marketplace.visualstudio.com/items?itemName=catalinpop.Geco101)

2. To add Geco to your solution, Right click on Solution and Select Add->New Project
![geco - add project](https://user-images.githubusercontent.com/1791839/35290716-b0da9cd4-0073-11e8-9533-12aa891d5e79.jpg)

3. The suggestion is to use "Tools" for the project name
![geco - add project - 2](https://user-images.githubusercontent.com/1791839/35290958-7df0bd2a-0074-11e8-85e4-ae2d4c015695.jpg)

4. Edit the `appSettings.json` and configure connection strings and the correct paths where the generated code will be placed (and other options as well)
![geco - change configurations](https://user-images.githubusercontent.com/1791839/35291230-60a3ba5a-0075-11e8-9586-79157739d7a6.jpg)

5. You can run Geco under a debugger (or at build, see appSettings).
![geco - run with debug](https://user-images.githubusercontent.com/1791839/35291682-bba06c0e-0076-11e8-94f8-ff09df57c78f.jpg)

6. At the interactive menu enter `1` (Generate EF Core Model) and Press `Enter`, next Press `y` then `Enter ` to confirm you want to **delete**!!! all the *.cs files in the folder and regenerate them (If you do not want this, set the CleanFilesPattern in appSettings.json from *.cs to empty string "".

![geco - generate model](https://user-images.githubusercontent.com/1791839/35292477-46c8cb1c-0079-11e8-92eb-78ed2e182751.jpg)


P.S There's currently a known issue if there are database triggers on the target database, then reading database metadata crashes Geco. A temp fix until the new version is released is to replace the following code in `SqlServerMetadataProvider.cs`:

```CSharp
        protected override IEnumerable<TriggerInfo> LoadTriggerInfo()
        {
            return Query<TriggerInfo>(
                @"SELECT 
                    tr.name, OBJECT_NAME(tr.parent_id) as  ParentTable, OBJECT_SCHEMA_NAME(tr.parent_id) as ParentTableSchema
                FROM sys.triggers tr");
        }
```

With:

```CSharp
        protected override IEnumerable<TriggerInfo> LoadTriggerInfo()
        {
            return Query<TriggerInfo>(
                @"SELECT 
                    tr.name, OBJECT_NAME(tr.parent_id) as  ParentTable, OBJECT_SCHEMA_NAME(tr.parent_id) as ParentTableSchema
                FROM sys.triggers tr 
                WHERE tr.parent_class <> 0");
        }
```
