### ISSUE TITLE
Why some tables were ignored ?

### ISSUE THREAD

**Issue by ghost** [iQuarc/Geco#9]
Some tables were ignored.
When i execute your query to list all the tables with my own sql provider i have 161 tables :
```
SELECT 
t.name as Name, 
OBJECT_SCHEMA_NAME(t.object_id) as [SchemaName], 
t.is_tracked_by_cdc
FROM sys.tables t
```

When i debug the method LoadMetadata() the result of LoadTables() was 147 tables !
Do you know why ?

**Comment by popcatalin81** [comment]
@sorcer1  there should not be any differences. 

Please check the following: 
 - The same server is used.
 - The same database is selected (USE [DatabaseName].
 - The same User is used in the connection (Access rights per user can limit the number of items visible)

**Comment by ghost** [comment]
I only have one server.
All the tables are in same database.
The same user is used for Geco and for when i launch my request manually.

**Comment by popcatalin81** [comment]
@sorcer1 I've tried several scenarios, I still get the same numbers of tables from Geco and from Management Studio. If you could provide some more info I will investigate more.

**Comment by ghost** [comment]
Perhaps if i send you one sql file to create 2 of mine tables with one table parsed by Geco and another one wich is not parsed by Geco ?

**Comment by popcatalin81** [comment]
That would be great. You can sent it at: pop [dot] catalin [at] gmail [dot] com

**Comment by popcatalin81** [comment]
Closing. Please feel free to reopen you have new info about this.

**Comment by ghost** [comment]
I solved it by using another user in database connection string.

When i check the differences between the 2 logins i see the working login have this roles :
[sysadmin]
[securityadmin]
[serveradmin]
[processadmin]
[diskadmin]
[dbcreator]
[bulkadmin]
